### ISSUE TITLE
Bot should republish URL to the channel once it starts playing

### ISSUE THREAD

**Issue by danvalente** [jmsdnns/pawn#1]
When a [new song starts playing ](https://github.com/jmsdnns/pawn/blob/main/app/bot/audio.js#L198-L204)the bot should republish the URL of that song to the channel. This would allow Discord to prettify the metadata for what is playing so everyone would know!

**Comment by jmsdnns** [comment]
This was added with the following line.

https://github.com/jmsdnns/pawn/commit/5481e644ca031793f091e2921de34c0d8e0cec40#diff-e0aa8de739d5d7a95dd7625e6498518f33a029091e35f93ee530268a6db6d6b1R41
